# Generated by Django 3.0.6 on 2020-11-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=100)),
                ('question2', models.CharField(max_length=100)),
                ('question3', models.CharField(max_length=100)),
                ('question4', models.CharField(max_length=100)),
                ('question5', models.CharField(max_length=100)),
                ('question6', models.CharField(max_length=100)),
                ('question7', models.CharField(max_length=100)),
                ('question8', models.CharField(max_length=100)),
                ('question9', models.CharField(max_length=100)),
                ('question10', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
    ]
