# Generated by Django 3.0.6 on 2020-11-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question10',
            new_name='option1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question2',
            new_name='option2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question3',
            new_name='option3',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question4',
            new_name='option4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question5',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question6',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question7',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question8',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question9',
        ),
    ]
