# Generated by Django 3.0.6 on 2020-11-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20201105_1826'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='question',
            new_name='Questions',
        ),
    ]
