# Generated by Django 3.0.6 on 2020-11-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20201105_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='question1',
            new_name='question',
        ),
    ]
